--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: plataforma; Type: TABLE; Schema: public; Owner: usuario
--

CREATE TABLE public.plataforma (
    nombreplataforma character varying(30) NOT NULL
);


ALTER TABLE public.plataforma OWNER TO usuario;

--
-- Name: videojuego; Type: TABLE; Schema: public; Owner: usuario
--

CREATE TABLE public.videojuego (
    id integer NOT NULL,
    imagen character varying(256),
    nombre character varying(256),
    precio character varying(20),
    tipocompra character varying(256),
    nombreplataforma character varying(30)
);


ALTER TABLE public.videojuego OWNER TO usuario;

--
-- Name: videojuego_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario
--

ALTER TABLE public.videojuego ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.videojuego_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: plataforma; Type: TABLE DATA; Schema: public; Owner: usuario
--

COPY public.plataforma (nombreplataforma) FROM stdin;
"PLAYSTATION 4"
"PLAYSTATION 5"
"PC SOFTWARE"
"XBOX ONE"
"NINTENDO SWITCH"
\.


--
-- Data for Name: videojuego; Type: TABLE DATA; Schema: public; Owner: usuario
--

COPY public.videojuego (id, imagen, nombre, precio, tipocompra, nombreplataforma) FROM stdin;
1	"https://media.game.es/COVERV2/3D_L/193/193851.png"	"Horizon Forbidden West Edicion Coleccionista"	"199 '95 €"	"COMPRAR"	"PLAYSTATION 4"
2	"https://media.game.es/COVERV2/3D_L/196/196770.png"	"Elden Ring Edicion Coleccionista"	"199 '95 €"	"COMPRAR"	"PLAYSTATION 5"
3	"https://media.game.es/COVERV2/3D_L/196/196771.png"	"Elden Ring Edicion Coleccionista"	"199 '95 €"	"COMPRAR"	"PC SOFTWARE"
4	"https://media.game.es/COVERV2/3D_L/196/196769.png"	"Elden Ring Edicion Coleccionista"	"199 '95 €"	"COMPRAR"	"XBOX ONE"
5	"https://media.game.es/COVERV2/3D_L/186/186529.png"	"Pecaminosa Collector Edition"	"3 €"	"RESERVAR"	"PLAYSTATION 4"
6	"https://media.game.es/COVERV2/3D_L/170/170211.png"	"Zenith: Collector's Edition"	"3 €"	"RESERVAR"	"NINTENDO SWITCH"
7	"https://media.game.es/COVERV2/3D_L/199/199744.png"	"Final Vendetta Collectors Edition"	"3 €"	"RESERVAR"	"NINTENDO SWITCH"
8	"https://media.game.es/COVERV2/3D_L/189/189777.png"	"Made In Abbys - Collectors Edition"	"3 €"	"RESERVAR"	"NINTENDO SWITCH"
9	"https://media.game.es/COVERV2/3D_L/189/189776.png"	"Made In Abbys - Collectors Edition"	"3 €"	"RESERVAR"	"PLAYSTATION 4"
10	"https://media.game.es/COVERV2/3D_L/199/199742.png"	"Final Vendetta Collectors Edition"	"3 €"	"RESERVAR"	"PLAYSTATION 4"
11	"https://media.game.es/COVERV2/3D_L/187/187155.png"	"Beholder 2"	"3 €"	"RESERVAR"	"NINTENDO SWITCH"
12	"https://media.game.es/COVERV2/3D_L/187/187156.png"	"Beholder 2"	"3 €"	"RESERVAR"	"PLAYSTATION 4"
13	"https://media.game.es/COVERV2/3D_L/170/170215.png"	"Distrust: Collector's Edition"	"3 €"	"RESERVAR"	"NINTENDO SWITCH"
14	"https://media.game.es/COVERV2/3D_L/199/199743.png"	"Final Vendetta Collectors Edition"	"3 €"	"RESERVAR"	"PLAYSTATION 5"
15	"https://media.game.es/COVERV2/3D_L/190/190470.png"	"Dying Light 2 Stay Human Collector's Edition"	"229 '95 €"	"COMPRAR"	"PLAYSTATION 4"
16	"https://media.game.es/COVERV2/3D_L/189/189171.png"	"Maldita Castilla Ed Coleccionista"	"49 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
17	"https://media.game.es/COVERV2/3D_L/162/162517.png"	"Final Fantasy XII The Zodiac Age"	"24 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
18	"https://media.game.es/COVERV2/3D_L/190/190472.png"	"Dying Light 2 Stay Human Collector's Edition"	"229 '95 €"	"COMPRAR"	"XBOX ONE"
19	"https://media.game.es/COVERV2/3D_L/189/189991.png"	"Marvel's Guardians of the Galaxy Edición Cósmica Deluxe"	"79 '95 €"	"COMPRAR"	"XBOX ONE"
20	"https://media.game.es/COVERV2/3D_L/189/189990.png"	"Marvel's Guardians of the Galaxy Edición Cósmica Deluxe"	"79 '95 €"	"COMPRAR"	"PLAYSTATION 4"
21	"https://media.game.es/COVERV2/3D_L/182/182508.png"	"Neversong - Collector´s Edition"	"49 '95 €"	"COMPRAR"	"PLAYSTATION 4"
22	"https://media.game.es/COVERV2/3D_L/191/191164.png"	"Danganronpa Decadence Collector’s Edition"	"99 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
23	"https://media.game.es/COVERV2/3D_L/184/184014.png"	"Blasphemous - Edición Coleccionista"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
24	"https://media.game.es/COVERV2/3D_L/191/191963.png"	"Gearshifters Collector's Edition"	"34 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
25	"https://media.game.es/COVERV2/3D_L/190/190471.png"	"Dying Light 2 Stay Human Collector's Edition"	"229 '95 €"	"COMPRAR"	"PLAYSTATION 5"
26	"https://media.game.es/COVERV2/3D_L/190/190457.png"	"A Tale of Synapse Collector's Edition"	"49 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
27	"https://media.game.es/COVERV2/3D_L/188/188548.png"	"Oddworld Soulstorm - Collector's Oddition"	"149 '95 €"	"COMPRAR"	"PLAYSTATION 4"
28	"https://media.game.es/COVERV2/3D_L/170/170214.png"	"Beholder Complete Edition"	"34 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
29	"https://media.game.es/COVERV2/3D_L/188/188958.png"	"Alex Kidd in Miracle World DX Signature Edition"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
30	"https://media.game.es/COVERV2/3D_L/183/183662.png"	"Fighting Legends - Edición Coleccionista"	"79 '95 €"	"COMPRAR"	"PLAYSTATION 4"
31	"https://media.game.es/COVERV2/3D_L/182/182801.png"	"Crypt of the Necrodancer Collector´s Edition"	"39 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
32	"https://media.game.es/COVERV2/3D_L/142/142166.png"	"Biomutant Collector´s Edition"	"109 '95 €"	"COMPRAR"	"PLAYSTATION 4"
33	"https://media.game.es/COVERV2/3D_L/191/191793.png"	"Asterix & Obelix Slap Them All Edicion Coleccionista"	"79 '95 €"	"COMPRAR"	"PLAYSTATION 4"
34	"https://media.game.es/COVERV2/3D_L/182/182731.png"	"Train Sim World 2 - Collector´s Edition"	"49 '95 €"	"COMPRAR"	"PLAYSTATION 4"
35	"https://media.game.es/COVERV2/3D_L/189/189537.png"	"Sword of the Necromancer Edición Coleccionista"	"59 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
36	"https://media.game.es/COVERV2/3D_L/189/189538.png"	"Sword of the Necromancer Edición Coleccionista"	"59 '95 €"	"COMPRAR"	"PLAYSTATION 4"
37	"https://media.game.es/COVERV2/3D_L/191/191296.png"	"Farming Simulator 22 Edicion Coleccionista"	"69 '95 €"	"COMPRAR"	"PC SOFTWARE"
38	"https://media.game.es/COVERV2/3D_L/170/170216.png"	"Do not Feed the Monkeys: Collector's Edition"	"39 '95 €"	"COMPRAR"	"PLAYSTATION 4"
39	"https://media.game.es/COVERV2/3D_L/184/184012.png"	"Blasphemous - Edición Coleccionista"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
40	"https://media.game.es/COVERV2/3D_L/178/178433.png"	"Dead Cells The Prisioner's Edition"	"119 '95 €"	"COMPRAR"	"PLAYSTATION 4"
41	"https://media.game.es/COVERV2/3D_L/181/181264.png"	"Kingdoms of Amalur Re-Reckoning - Edición Coleccionista"	"109 '95 €"	"COMPRAR"	"PLAYSTATION 4"
42	"https://media.game.es/COVERV2/3D_L/177/177986.png"	"Marvel´s Avengers Edición Más Poderosa de la Tierra"	"159 '95 €"	"COMPRAR"	"XBOX ONE"
43	"https://media.game.es/COVERV2/3D_L/182/182507.png"	"Neversong - Collector´s Edition"	"49 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
44	"https://media.game.es/COVERV2/3D_L/177/177535.png"	"1971 Project Helios Collector´S Edition"	"29 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
45	"https://media.game.es/COVERV2/3D_L/191/191794.png"	"Asterix & Obelix Slap Them All Edicion Coleccionista"	"79 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
46	"https://media.game.es/COVERV2/3D_L/170/170212.png"	"Hard West: Collector's Edition"	"39 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
47	"https://media.game.es/COVERV2/3D_L/179/179817.png"	"Desperados III - Collector's Edition"	"84 '95 €"	"COMPRAR"	"PC SOFTWARE"
48	"https://media.game.es/COVERV2/3D_L/191/191962.png"	"Gearshifters Collector's Edition"	"34 '95 €"	"COMPRAR"	"PLAYSTATION 4"
49	"https://media.game.es/COVERV2/3D_L/166/166777.png"	"Dragon Ball Z: Kakarot Collector Edition"	"239 '95 €"	"COMPRAR"	"PLAYSTATION 4"
50	"https://media.game.es/COVERV2/3D_L/182/182799.png"	"Crypt of the Necrodancer Collector´s Edition"	"39 '95 €"	"COMPRAR"	"PLAYSTATION 4"
51	"https://media.game.es/COVERV2/3D_L/177/177985.png"	"Marvel´s Avengers Edición Más Poderosa de la Tierra"	"159 '95 €"	"COMPRAR"	"PLAYSTATION 4"
52	"https://media.game.es/COVERV2/3D_L/177/177534.png"	"1971 Project Helios Collector´S Edition"	"29 '95 €"	"COMPRAR"	"PLAYSTATION 4"
53	"https://media.game.es/COVERV2/3D_L/171/171688.png"	"Destroy All Humans! DNA Collector's Edition"	"109 '95 €"	"COMPRAR"	"PLAYSTATION 4"
54	"https://media.game.es/COVERV2/3D_L/180/180832.png"	"Re:Zero - The Prophecy Of The Throne Limited"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
55	"https://media.game.es/COVERV2/3D_L/171/171806.png"	"AI:Somnium Files Edicion Coleccionista"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
56	"https://media.game.es/COVERV2/3D_L/177/177536.png"	"1971 Project Helios Collector´S Edition"	"29 '95 €"	"COMPRAR"	"PC SOFTWARE"
57	"https://media.game.es/COVERV2/3D_L/170/170210.png"	"Lovecraft´s Untold Stories: Collector's Edition"	"29 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
58	"https://media.game.es/COVERV2/3D_L/178/178434.png"	"Dead Cells The Prisioner's Edition"	"119 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
59	"https://media.game.es/COVERV2/3D_L/181/181265.png"	"Kingdoms of Amalur Re-Reckoning - Edición Coleccionista"	"109 '95 €"	"COMPRAR"	"XBOX ONE"
60	"https://media.game.es/COVERV2/3D_L/180/180590.png"	"Captain Tsubasa: Rise of new Champions Ed Col"	"99 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
61	"https://media.game.es/COVERV2/3D_L/172/172746.png"	"Train Sim World Collectors Edition"	"44 '95 €"	"COMPRAR"	"PLAYSTATION 4"
62	"https://media.game.es/COVERV2/3D_L/170/170213.png"	"Beholder CE: Collector's Edition"	"29 '95 €"	"COMPRAR"	"PLAYSTATION 4"
63	"https://media.game.es/COVERV2/3D_L/166/166491.png"	"BlackSad Under the Skin Edicion Coleccionista"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
64	"https://media.game.es/COVERV2/3D_L/177/177339.png"	"The Elder Scrolls Online Greymoor Collector’s Upgrade"	"99 '95 €"	"COMPRAR"	"PLAYSTATION 4"
65	"https://media.game.es/COVERV2/3D_L/171/171561.png"	"WRC 8 Edición Coleccionista"	"44 '95 €"	"COMPRAR"	"PLAYSTATION 4"
66	"https://media.game.es/COVERV2/3D_L/170/170732.png"	"NeverWinter Nights Enhanced Edition Edición Coleccionista"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
67	"https://media.game.es/COVERV2/3D_L/170/170734.png"	"Icewind Dale Enhanced Edition Edición Colecionista"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
68	"https://media.game.es/COVERV2/3D_L/172/172747.png"	"Train Sim World Collectors Edition"	"44 '95 €"	"COMPRAR"	"XBOX ONE"
69	"https://media.game.es/COVERV2/3D_L/170/170209.png"	"Lovecraft Untold Stories: Collector's Edition"	"34 '95 €"	"COMPRAR"	"PLAYSTATION 4"
70	"https://media.game.es/COVERV2/3D_L/171/171680.png"	"Asterix y Obelix XXL 3 The Crystal Menhir Collector Edition"	"49 '95 €"	"COMPRAR"	"PLAYSTATION 4"
71	"https://media.game.es/COVERV2/3D_L/171/171562.png"	"WRC 8 Edición Coleccionista"	"44 '95 €"	"COMPRAR"	"XBOX ONE"
72	"https://media.game.es/COVERV2/3D_L/163/163908.png"	"Monster Jam Steel Titans - Collector's Edition"	"59 '95 €"	"COMPRAR"	"XBOX ONE"
73	"https://media.game.es/COVERV2/3D_L/186/186789.png"	"Terminator: Resistance Enhanced - Collector´s Edition"	"39 '95 €"	"COMPRAR"	"PLAYSTATION 5"
74	"https://media.game.es/COVERV2/3D_L/188/188549.png"	"Oddworld Soulstorm - Day One Oddition"	"34 '95 €"	"COMPRAR"	"PLAYSTATION 5"
75	"https://media.game.es/COVERV2/3D_L/170/170217.png"	"Do not Feed the Monkeys: Collector's Edition"	"44 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
76	"https://media.game.es/COVERV2/3D_L/188/188550.png"	"Oddworld Soulstorm - Collector's Oddition"	"149 '95 €"	"COMPRAR"	"PLAYSTATION 5"
77	"https://media.game.es/COVERV2/3D_L/142/142165.png"	"Biomutant Collector´s Edition"	"109 '95 €"	"COMPRAR"	"PC SOFTWARE"
78	"https://media.game.es/COVERV2/3D_L/142/142167.png"	"Biomutant Collector´s Edition"	"109 '95 €"	"COMPRAR"	"XBOX ONE"
79	"https://media.game.es/COVERV2/3D_L/189/189408.png"	"Blasphemous - Edición Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
80	"https://media.game.es/COVERV2/3D_L/186/186030.png"	"Cyberpunk 2077 Edición Coleccionista"	"129 '95 €"	"COMPRAR"	"PLAYSTATION 4"
81	"https://media.game.es/COVERV2/3D_L/186/186031.png"	"Cyberpunk 2077 Edicion Coleccionista"	"129 '95 €"	"COMPRAR"	"XBOX ONE"
82	"https://media.game.es/COVERV2/3D_L/187/187307.png"	"Dead Cells The Prisioner's Edition (REACONDICIONADO)"	"99 '95 €"	"COMPRAR"	"PLAYSTATION 4"
83	"https://media.game.es/COVERV2/3D_L/179/179138.png"	"Bounty Battle Signature Edition"	"54 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
84	"https://media.game.es/COVERV2/3D_L/179/179137.png"	"Bounty Battle Signature Edition"	"49 '95 €"	"COMPRAR"	"PLAYSTATION 4"
85	"https://media.game.es/COVERV2/3D_L/191/191512.png"	"Marvel´s Avengers Edición Más Poderosa de la Tierra (REACONDICIONADO)"	"124 '95 €"	"COMPRAR"	"XBOX ONE"
86	"https://media.game.es/COVERV2/3D_L/191/191506.png"	"Captain Tsubasa: Rise of new Champions Ed Col (REACONDICIONADO)"	"84 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
87	"https://media.game.es/COVERV2/3D_L/189/189608.png"	"House Flipper Signature Edition (REACONDICIONADO)"	"49 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
88	"https://media.game.es/COVERV2/3D_L/180/180270.png"	"House Flipper Signature Edition"	"59 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
89	"https://media.game.es/COVERV2/3D_L/180/180269.png"	"House Flipper Signature Edition"	"54 '95 €"	"COMPRAR"	"PLAYSTATION 4"
90	"https://media.game.es/COVERV2/3D_L/171/171687.png"	"Destroy All Humans! DNA Collector's Edition"	"109 '95 €"	"COMPRAR"	"PC SOFTWARE"
91	"https://media.game.es/COVERV2/3D_L/171/171689.png"	"Destroy All Humans! DNA Collector's Edition"	"109 '95 €"	"COMPRAR"	"XBOX ONE"
92	"https://media.game.es/COVERV2/3D_L/178/178951.png"	"Dungeons of the Endless Signature Edition"	"49 '95 €"	"COMPRAR"	"PLAYSTATION 4"
93	"https://media.game.es/COVERV2/3D_L/178/178952.png"	"Dungeons of the Endless Signature Edition"	"54 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
94	"https://media.game.es/COVERV2/3D_L/174/174925.png"	"Bob Esponja Battle for Bikini Bottom - Rehydrated - Shiny Edition"	"149 '95 €"	"COMPRAR"	"PLAYSTATION 4"
95	"https://media.game.es/COVERV2/3D_L/174/174926.png"	"Bob Esponja Battle for Bikini Bottom - Rehydrated - Shiny Edition"	"149 '95 €"	"COMPRAR"	"XBOX ONE"
96	"https://media.game.es/COVERV2/3D_L/174/174929.png"	"Bob Esponja Battle for Bikini Bottom - Rehydrated - F.U.N Edition"	"219 '95 €"	"COMPRAR"	"PLAYSTATION 4"
97	"https://media.game.es/COVERV2/3D_L/174/174930.png"	"Bob Esponja Battle for Bikini Bottom - Rehydrated - F.U.N Edition"	"219 '95 €"	"COMPRAR"	"XBOX ONE"
98	"https://media.game.es/COVERV2/3D_L/174/174932.png"	"Bob Esponja Battle for Bikini Bottom - Rehydrated - F.U.N Edition"	"299 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
99	"https://media.game.es/COVERV2/3D_L/179/179818.png"	"Desperados III - Collector's Edition"	"94 '95 €"	"COMPRAR"	"PLAYSTATION 4"
100	"https://media.game.es/COVERV2/3D_L/179/179819.png"	"Desperados III - Collector's Edition"	"94 '95 €"	"COMPRAR"	"XBOX ONE"
101	"https://media.game.es/COVERV2/3D_L/177/177340.png"	"The Elder Scrolls Online Greymoor Collector’s Upgrade"	"99 '95 €"	"COMPRAR"	"XBOX ONE"
102	"https://media.game.es/COVERV2/3D_L/170/170728.png"	"Baldur´s Gate Enhanced Edition Pack Edición Coleccionista"	"79 '95 €"	"COMPRAR"	"PLAYSTATION 4"
103	"https://media.game.es/COVERV2/3D_L/178/178598.png"	"Baldur´s Gate Enhanced Edition Pack Edición Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
104	"https://media.game.es/COVERV2/3D_L/178/178886.png"	"Baldur´s Gate Enhanced Edition Pack Edición Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
105	"https://media.game.es/COVERV2/3D_L/187/187308.png"	"Baldur´s Gate Enhanced Edition Pack Edición Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"XBOX ONE"
106	"https://media.game.es/COVERV2/3D_L/170/170733.png"	"NeverWinter Nights Enhanced Edition Edición Coleccionista"	"69 '95 €"	"COMPRAR"	"XBOX ONE"
107	"https://media.game.es/COVERV2/3D_L/189/189720.png"	"NeverWinter Nights Enhanced Edition Edición Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"XBOX ONE"
108	"https://media.game.es/COVERV2/3D_L/184/184862.png"	"NeverWinter Nights Enhanced Edition Edición Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
109	"https://media.game.es/COVERV2/3D_L/179/179083.png"	"NeverWinter Nights Enhanced Edition Edicion Coleccionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
110	"https://media.game.es/COVERV2/3D_L/170/170731.png"	"NeverWinter Nights Enhanced Edition Edicion Coleccionista"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
111	"https://media.game.es/COVERV2/3D_L/199/199953.png"	"Icewind Dale Enhanced Edition Edición Colecionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
112	"https://media.game.es/COVERV2/3D_L/184/184483.png"	"Icewind Dale Enhanced Edition Edición Colecionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"PLAYSTATION 4"
113	"https://media.game.es/COVERV2/3D_L/187/187750.png"	"Icewind Dale Enhanced Edition Edición Colecionista (REACONDICIONADO)"	"69 '95 €"	"COMPRAR"	"XBOX ONE"
114	"https://media.game.es/COVERV2/3D_L/170/170735.png"	"Icewind Dale Enhanced Edition Edición Colecionista"	"69 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
115	"https://media.game.es/COVERV2/3D_L/170/170736.png"	"Icewind Dale Enhanced Edition Edición Colecionista"	"69 '95 €"	"COMPRAR"	"XBOX ONE"
116	"https://media.game.es/COVERV2/3D_L/177/177950.png"	"Dragon Ball Z: Kakarot Collector Edition (REACONDICIONADO)"	"134 '95 €"	"COMPRAR"	"PLAYSTATION 4"
117	"https://media.game.es/COVERV2/3D_L/177/177951.png"	"Dragon Ball Z: Kakarot Collector Edition (REACONDICIONADO)"	"134 '95 €"	"COMPRAR"	"XBOX ONE"
118	"https://media.game.es/COVERV2/3D_L/166/166779.png"	"Dragon Ball Z: Kakarot Collector Edition"	"239 '95 €"	"COMPRAR"	"XBOX ONE"
119	"https://media.game.es/COVERV2/3D_L/171/171679.png"	"Asterix y Obelix XXL 3 The Crystal Menhir Collector Edition"	"49 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
120	"https://media.game.es/COVERV2/3D_L/185/185536.png"	"Lovecraft Untold Stories: Collector's Edition (REACONDICIONADO)"	"29 '95 €"	"COMPRAR"	"PLAYSTATION 4"
121	"https://media.game.es/COVERV2/3D_L/155/155022.png"	"Rage 2 Collectors Edition"	"79 '95 €"	"COMPRAR"	"PC SOFTWARE"
122	"https://media.game.es/COVERV2/3D_L/162/162481.png"	"Generation Zero Collectors Edition"	"59 '95 €"	"COMPRAR"	"PC SOFTWARE"
123	"https://media.game.es/COVERV2/3D_L/162/162482.png"	"Generation Zero Collectors Edition"	"59 '95 €"	"COMPRAR"	"PLAYSTATION 4"
124	"https://media.game.es/COVERV2/3D_L/198/198744.png"	"Generation Zero Collectors Edition (REACONDICIONADO)"	"49 '95 €"	"COMPRAR"	"PLAYSTATION 4"
125	"https://media.game.es/COVERV2/3D_L/162/162483.png"	"Generation Zero Collectors Edition"	"59 '95 €"	"COMPRAR"	"XBOX ONE"
126	"https://media.game.es/COVERV2/3D_L/152/152684.png"	"Asterix y Obelix XXL2 Collector Edition"	"59 '95 €"	"COMPRAR"	"NINTENDO SWITCH"
127	"https://media.game.es/COVERV2/3D_L/159/159856.png"	"Elder Scrolls Online Summerset Collectors Edition (REACONDICIONADO)"	"59 '95 €"	"COMPRAR"	"XBOX ONE"
128	"https://media.game.es/COVERV2/3D_L/102/102758.png"	"Killer is Dead Nightmare Edition"	"7 '95 €"	"COMPRAR"	"PC SOFTWARE"
\.


--
-- Name: videojuego_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario
--

SELECT pg_catalog.setval('public.videojuego_id_seq', 128, true);


--
-- Name: plataforma plataforma_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario
--

ALTER TABLE ONLY public.plataforma
    ADD CONSTRAINT plataforma_pkey PRIMARY KEY (nombreplataforma);


--
-- Name: videojuego videojuego_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario
--

ALTER TABLE ONLY public.videojuego
    ADD CONSTRAINT videojuego_pkey PRIMARY KEY (id);


--
-- Name: videojuego fke1dooi4yt6s980skh5jdjm3b5; Type: FK CONSTRAINT; Schema: public; Owner: usuario
--

ALTER TABLE ONLY public.videojuego
    ADD CONSTRAINT fke1dooi4yt6s980skh5jdjm3b5 FOREIGN KEY (nombreplataforma) REFERENCES public.plataforma(nombreplataforma);


--
-- PostgreSQL database dump complete
--

